### PR TITLE
SEN-1231 & SEN-1236 -- jeckyl setup

### PR DESCRIPTION
**Pull request by noTxt**
**testing:**
- checkout `noTxt:SEN-1229-a`
- `bundle install` ( `gem install bundler` if you don't have bundler )
- `bower install`
- `bundle exec jekyll serve --drafts`
- visit [Local site](http://localhost:4000/) and inspect theme

**ticket:**
https://cascadeenergy.atlassian.net/browse/SEN-1231 & https://cascadeenergy.atlassian.net/browse/SEN-1236
epic - https://cascadeenergy.atlassian.net/browse/SEN-1227

**note:**
this content creation is delt with in:
https://cascadeenergy.atlassian.net/browse/SEN-1234
https://cascadeenergy.atlassian.net/browse/SEN-1235

### CODE REVIEW

**Comment by noTxt** [comment]
@cberube previous PR got borked when I reset the branch to an earlier commit

**Comment by noTxt** [comment]
https://github.com/CascadeEnergy/CascadeEnergy.github.io/pull/4

**Comment by cberube** [comment]
:ok:

**Comment by nackjicholson** [comment]
:ok: :shipit:

**Pull request merged**
